version: "3"
services:
  postgresql:
    image: postgres
    container_name: project
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=misha
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DATABASE=prDb
    command: postgres
    restart: always


  redis:
    image: redis:alpine3.14
    container_name: redis-lesson
    ports:
      - "6379:6379"